---
- name: Configure WLAN - phsa-staff
  aireos_config:
    lines:
      - wlan disable 101
      - wlan create 101 phsa-staff phsa-staff
      - wlan nasid none 101
      - wlan mdns disable 101
      - wlan nac snmp disable 101
      - wlan nac radius disable 101
      - wlan multicast interface 101 disable
      - wlan aaa-override enable 101
      - wlan band-select allow disable 101
      - wlan load-balance allow disable 101 
      - wlan assisted-roaming prediction disable 101
      - wlan assisted-roaming neighbor-list enable 101
      - wlan assisted-roaming dual-list disable 101
      - wlan dms enable 101
      - wlan bssmaxidle enable 101
      - wlan bss-transition enable 101
      - wlan bss-transition disassociation-imminent timer 200 101
      - wlan bss-transition disassociation-imminent oproam-timer 40 101
      - wlan flow 101 monitor 'Netflow Monitor BCS-CW-PI-001' enable
      - wlan multicast buffer disable 0 101
      - wlan session-timeout 101 28800
      - wlan flexconnect local-switching 101 enable
      - wlan flexconnect learn-ipaddr 101 enable
      - wlan flexconnect vlan-central-switching 101 enable
      - wlan avc 101 visibility enable 
      - wlan wgb broadcast-tagging disable 101 
      - wlan radius_server auth add 101 1 
      - wlan radius_server auth add 101 2 
      - wlan radius_server acct add 101 1 
      - wlan radius_server acct add 101 2 
      - wlan security splash-page-web-redir disable 101
      - wlan security wpa akm 802.1x enable 101
      - wlan security wpa akm cckm timestamp-tolerance  1000 101
      - wlan security ft over-the-ds disable 101
      - wlan security wpa gtk-random disable 101
      - wlan security pmf association-comeback 1 101
      - wlan security pmf saquery-retrytimeout 200 101
      - wlan profiling radius dhcp disable 101
      - wlan profiling radius http disable 101
      - wlan mobility selective-reanchoring disable 101
      - wlan enable 101
  when: "'phsa-staff' in include_wlans"

- name: Configure WLAN - vch
  aireos_config:
    lines:
      - wlan disable 102
      - wlan create 102 vch vch
      - wlan nasid none 102 
      - wlan mdns disable 102 
      - wlan nac snmp disable 102 
      - wlan nac radius disable 102 
      - wlan multicast interface 102 disable
      - wlan aaa-override enable 102
      - wlan broadcast-ssid disable 102
      - wlan band-select allow disable 102 
      - wlan load-balance allow disable 102 
      - wlan assisted-roaming prediction disable 102
      - wlan assisted-roaming neighbor-list enable 102
      - wlan assisted-roaming dual-list disable 102
      - wlan dms enable 102
      - wlan bssmaxidle enable 102
      - wlan bss-transition enable 102 
      - wlan bss-transition disassociation-imminent timer 200 102
      - wlan bss-transition disassociation-imminent oproam-timer 40 102
      - wlan flow 102 monitor 'Netflow Monitor BCS-CW-PI-001' enable
      - wlan multicast buffer disable 0 102
      - wlan session-timeout 102 28800
      - wlan flexconnect local-switching 102 enable
      - wlan flexconnect learn-ipaddr 102 enable
      - wlan flexconnect vlan-central-switching 102 enable
      - wlan avc 102 visibility enable
      - wlan wgb broadcast-tagging disable 102 
      - wlan radius_server auth add 102 1 
      - wlan radius_server auth add 102 2 
      - wlan radius_server acct add 102 1 
      - wlan radius_server acct add 102 2 
      - wlan security splash-page-web-redir disable 102
      - wlan security wpa akm 802.1x enable 102 
      - wlan security wpa akm cckm timestamp-tolerance  1000 102
      - wlan security ft over-the-ds disable 102
      - wlan security wpa gtk-random disable 102
      - wlan security pmf association-comeback 1 102
      - wlan security pmf saquery-retrytimeout 200 102
      - wlan profiling radius dhcp disable 102 
      - wlan profiling radius http disable 102 
      - wlan mobility selective-reanchoring disable 102
      - wlan enable 102
  when: "'vch' in include_wlans"

- name: Configure WLAN - vch-staff
  aireos_config:
    lines:
      - wlan disable 103
      - wlan create 103 vch-staff vch-staff
      - wlan nasid none 103 
      - wlan mdns disable 103 
      - wlan nac snmp disable 103 
      - wlan nac radius disable 103 
      - wlan multicast interface 103 disable
      - wlan aaa-override enable 103
      - wlan band-select allow disable 103 
      - wlan load-balance allow disable 103 
      - wlan assisted-roaming prediction disable 103
      - wlan assisted-roaming neighbor-list enable 103
      - wlan assisted-roaming dual-list disable 103
      - wlan dms enable 103
      - wlan bssmaxidle enable 103
      - wlan bss-transition enable 103
      - wlan bss-transition disassociation-imminent timer 200 103
      - wlan bss-transition disassociation-imminent oproam-timer 40 103
      - wlan flow 103 monitor 'Netflow Monitor BCS-CW-PI-001' enable
      - wlan multicast buffer disable 0 103
      - wlan session-timeout 103 28800
      - wlan flexconnect local-switching 103 enable
      - wlan flexconnect learn-ipaddr 103 enable
      - wlan flexconnect vlan-central-switching 103 enable
      - wlan avc 103 visibility enable 
      - wlan wgb broadcast-tagging disable 103 
      - wlan radius_server auth add 103 1 
      - wlan radius_server auth add 103 2 
      - wlan radius_server acct add 103 1 
      - wlan radius_server acct add 103 2 
      - wlan security splash-page-web-redir disable 103
      - wlan security wpa akm 802.1x enable 103
      - wlan security wpa akm cckm timestamp-tolerance  1000 103
      - wlan security ft over-the-ds disable 103
      - wlan security wpa gtk-random disable 103
      - wlan security pmf association-comeback 1 103
      - wlan security pmf saquery-retrytimeout 200 103
      - wlan dhcp_server 103 0.0.0.0 required 
      - wlan profiling radius dhcp disable 103 
      - wlan profiling radius http disable 103 
      - wlan mobility selective-reanchoring disable 103
      - wlan enable 103
  when: "'vch-staff' in include_wlans"

- name: Configure WLAN - Sponsored-Guest
  aireos_config:
    lines:
      - wlan disable 132
      - wlan create 132 Sponsored-Guest Sponsored-Guest
      - wlan nasid none 132 
      - wlan mdns disable 132 
      - wlan mdns profile 132 "default-mdns-profile" 
      - wlan nac snmp disable 132 
      - wlan nac radius enable 132 
      - wlan multicast interface 132 disable
      - wlan aaa-override enable 132
      - wlan band-select allow disable 132 
      - wlan load-balance allow disable 132 
      - wlan assisted-roaming prediction disable 132
      - wlan assisted-roaming neighbor-list enable 132
      - wlan assisted-roaming dual-list disable 132
      - wlan dms enable 132
      - wlan bssmaxidle enable 132
      - wlan bss-transition enable 132
      - wlan bss-transition disassociation-imminent timer 200 132
      - wlan bss-transition disassociation-imminent oproam-timer 40 132
      - wlan flow 132 monitor 'Netflow Monitor BCS-CW-PI-001' enable
      - wlan multicast buffer disable 0 132
      - wlan mac-filtering enable 132
      - wlan qos 132 bronze 
      - wlan session-timeout 132 disable
      - wlan avc 132 visibility enable  
      - wlan wgb broadcast-tagging disable 132 
      - wlan security wpa disable 132
      - wlan radius_server auth add 132 1 
      - wlan radius_server auth add 132 2 
      - wlan radius_server acct add 132 1 
      - wlan radius_server acct add 132 2 
      - wlan security splash-page-web-redir disable 132
      - wlan security wpa akm cckm timestamp-tolerance  1000 132
      - wlan security ft over-the-ds disable 132
      - wlan security wpa gtk-random disable 132
      - wlan security pmf association-comeback 1 132
      - wlan security pmf saquery-retrytimeout 200 132
      - wlan dhcp_server 132 0.0.0.0 required 
      - wlan peer-blocking drop 132
      - wlan profiling radius dhcp disable 132 
      - wlan profiling radius http disable 132 
      - wlan mobility selective-reanchoring disable 132
      - wlan enable 132
  when: "'Sponsored-Guest' in include_wlans"
