---
- name: Configure SNMP Configuration
  aireos_config:
    lines:
      - snmp community delete public
      - snmp community delete private
      - snmp version v2c disable
      - snmp version v3 enable
      - snmp v3user create zenoss rw hmacsha aescfb128 {{ snmp_zenoss }}
      - snmp v3user create cmxadmin rw hmacsha aescfb128 {{ snmp_cmxadmin }}
      - snmp v3user create bccss ro hmacsha aescfb128 {{ snmp_bccss }}
      - snmp v3user delete default